import { Resend } from "resend";
import { ImageResponse } from "next/og";
import { createSupabaseAdmin } from "@/lib/supabase-server";
import { publishImagePost, publishStory } from "@/lib/instagram";

// 43-day automated Instagram campaign for @devis.flow — one image post +
// matching story per day, content generated by Gemini and rotated across
// the pillars from .claude/instagram-strategy.md. Runs via Vercel Cron
// (/api/instagram/daily-post, see vercel.json). No video/Reels here — those
// still require the Remotion pipeline (devisflow-video/), which needs a
// real browser and isn't a good fit for a serverless function.
//
// Progress is tracked in the `instagram_campaign_posts` table (day_number is
// unique), not in .claude/instagram-log.md — that file is for manual/dev-
// session work only and isn't deployed.

const CAMPAIGN_TOTAL_DAYS = 43;
const ALERT_EMAIL = process.env.CONTACT_EMAIL ?? "nathan.makambo23@gmail.com";
const SEND_FROM = "DevisFlow <equipe@devis-flow.fr>";

const PILLARS = [
  { key: "astuce", label: "Astuce devis/métier (ex: erreurs qui font perdre un chantier, comment chiffrer vite)" },
  { key: "avant_apres", label: "Avant/après chantier — temps gagné sur le devis grâce à DevisFlow" },
  { key: "preuve_produit", label: "Preuve produit — ce à quoi ressemble un devis DevisFlow, sans jargon technique" },
  { key: "urgence_efacture", label: "Urgence e-facture obligatoire septembre 2026 — DevisFlow déjà conforme Factur-X" },
  { key: "temoignage", label: "Témoignage artisan — bénéfice concret d'utiliser DevisFlow (fictif mais crédible, jamais de fausse citation attribuée)" },
  { key: "coulisses", label: "Coulisses / pourquoi DevisFlow existe — ton humain, proche des artisans" },
] as const;

const GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta";
const GEMINI_MODEL = "gemini-2.5-flash";

interface GeneratedContent {
  headline: string;
  caption: string;
}

async function determineNextDayStep(): Promise<{ dayNumber: number; done: boolean }> {
  "use step";
  const admin = createSupabaseAdmin();
  const { count } = await admin
    .from("instagram_campaign_posts")
    .select("id", { count: "exact", head: true })
    .eq("status", "posted");
  const dayNumber = (count ?? 0) + 1;
  return { dayNumber, done: dayNumber > CAMPAIGN_TOTAL_DAYS };
}

async function generateContentStep(pillarLabel: string): Promise<GeneratedContent> {
  "use step";
  const admin = createSupabaseAdmin();
  const { data: recent } = await admin
    .from("instagram_campaign_posts")
    .select("caption")
    .eq("status", "posted")
    .order("day_number", { ascending: false })
    .limit(5);
  const recentCaptions = (recent ?? []).map((r) => r.caption as string).filter(Boolean);

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error("GEMINI_API_KEY manquant");

  const prompt = `Tu es le community manager de DevisFlow, SaaS de génération de devis IA pour artisans et TPE/PME du BTP français (plombiers, électriciens, peintres, maçons). Ton "artisan à artisan", jamais robotique, jamais corporate. Deadline e-facture obligatoire septembre 2026 est un angle marketing légitime.

Génère UNE publication Instagram sur ce pilier : "${pillarLabel}".

Contraintes strictes :
- Ne jamais promettre ce que le produit ne fait pas réellement (devis générés par IA en 30 secondes, conformité Factur-X, relances automatiques J+3/J+7, essai gratuit 7 jours)
- Ne jamais inventer de statistique chiffrée précise non vérifiable (pas de "87% des artisans...")
- "headline" : accroche courte pour visuel carré, MAX 55 caractères, sans emoji, sans guillemets
- "caption" : légende Instagram complète en français (valeur concrète, CTA essai gratuit "lien en bio"), emojis avec parcimonie (2-4 max), termine par 8-10 hashtags pertinents BTP/artisanat/SaaS français

Ne répète pas ces légendes déjà publiées récemment (thème et formulation différents) :
${recentCaptions.length ? recentCaptions.map((c, i) => `${i + 1}. ${c.slice(0, 150)}...`).join("\n") : "(aucune)"}

Réponds UNIQUEMENT avec un JSON valide, sans markdown, format exact : {"headline": "...", "caption": "..."}`;

  const res = await fetch(`${GEMINI_API_BASE}/models/${GEMINI_MODEL}:generateContent?key=${apiKey}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }] }),
  });
  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(`Gemini request failed (${res.status}): ${text.slice(0, 300)}`);
  }
  const data = (await res.json()) as { candidates?: { content?: { parts?: { text?: string }[] } }[] };
  const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text ?? "";
  const jsonMatch = rawText.match(/\{[\s\S]*\}/);
  if (!jsonMatch) throw new Error("Réponse IA invalide (pas de JSON trouvé)");
  const parsed = JSON.parse(jsonMatch[0]);
  if (!parsed.headline || !parsed.caption) throw new Error("Réponse IA incomplète (headline/caption manquant)");
  return { headline: parsed.headline, caption: parsed.caption };
}

async function renderImageStep(headline: string): Promise<string> {
  "use step";
  const response = new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          background: "linear-gradient(160deg, #0a2540 0%, #1e3a5f 55%, #E85D25 140%)",
          padding: 90,
          fontFamily: "Arial",
        }}
      >
        <div style={{ fontSize: 30, fontWeight: 700, color: "#f97316", letterSpacing: 3, marginBottom: 36, display: "flex" }}>
          DEVISFLOW
        </div>
        <div style={{ fontSize: 66, fontWeight: 900, color: "#ffffff", textAlign: "center", lineHeight: 1.2, display: "flex" }}>
          {headline}
        </div>
        <div style={{ fontSize: 27, color: "rgba(255,255,255,0.8)", marginTop: 56, display: "flex" }}>
          Essai gratuit 7 jours → devis-flow.fr
        </div>
      </div>
    ),
    { width: 1080, height: 1080 }
  );
  const arrayBuffer = await response.arrayBuffer();
  // Base64 so this plain object survives the step boundary (Buffer isn't a
  // serializable step-return type in the workflow sandbox).
  return Buffer.from(arrayBuffer).toString("base64");
}

async function uploadImageStep(imageBase64: string, dayNumber: number): Promise<string> {
  "use step";
  const admin = createSupabaseAdmin();
  const buffer = Buffer.from(imageBase64, "base64");
  const path = `campaign/day-${String(dayNumber).padStart(2, "0")}.png`;
  const { error } = await admin.storage.from("social-assets").upload(path, buffer, {
    contentType: "image/png",
    upsert: true,
  });
  if (error) throw new Error(`Upload Supabase échoué: ${error.message}`);
  const { data } = admin.storage.from("social-assets").getPublicUrl(path);
  return data.publicUrl;
}

async function publishStep(imageUrl: string, caption: string): Promise<{ postId: string; storyId: string }> {
  "use step";
  const postId = await publishImagePost(imageUrl, caption);
  const storyId = await publishStory(imageUrl);
  return { postId, storyId };
}

async function saveResultStep(input: {
  dayNumber: number;
  pillarKey: string;
  headline: string;
  caption: string;
  imageUrl: string;
  postId?: string;
  storyId?: string;
  status: "posted" | "failed";
  errorMessage?: string;
}): Promise<void> {
  "use step";
  const admin = createSupabaseAdmin();
  await admin.from("instagram_campaign_posts").upsert(
    {
      day_number: input.dayNumber,
      pillar: input.pillarKey,
      headline: input.headline,
      caption: input.caption,
      image_url: input.imageUrl,
      ig_media_id: input.postId ?? null,
      ig_story_id: input.storyId ?? null,
      status: input.status,
      error_message: input.errorMessage ?? null,
      posted_at: input.status === "posted" ? new Date().toISOString() : null,
    },
    { onConflict: "day_number" }
  );
}

async function alertStep(subject: string, message: string): Promise<void> {
  "use step";
  const resend = new Resend(process.env.RESEND_API_KEY);
  try {
    await resend.emails.send({
      from: SEND_FROM,
      to: ALERT_EMAIL,
      subject: `[DevisFlow Instagram] ${subject}`,
      text: message,
    });
  } catch (err) {
    console.error("[daily-instagram-post] Alert email failed:", err);
  }
}

export async function dailyInstagramPostWorkflow(): Promise<void> {
  "use workflow";

  const { dayNumber, done } = await determineNextDayStep();
  if (done) {
    console.log(`[daily-instagram-post] Campagne terminée (${CAMPAIGN_TOTAL_DAYS} jours) — rien à publier.`);
    return;
  }

  const pillar = PILLARS[(dayNumber - 1) % PILLARS.length];

  try {
    const { headline, caption } = await generateContentStep(pillar.label);
    const imageBase64 = await renderImageStep(headline);
    const imageUrl = await uploadImageStep(imageBase64, dayNumber);
    const { postId, storyId } = await publishStep(imageUrl, caption);
    await saveResultStep({
      dayNumber,
      pillarKey: pillar.key,
      headline,
      caption,
      imageUrl,
      postId,
      storyId,
      status: "posted",
    });

    if (dayNumber === CAMPAIGN_TOTAL_DAYS) {
      await alertStep(
        "Campagne 43 jours terminée",
        `La publication automatique quotidienne sur @devis.flow vient de publier son ${CAMPAIGN_TOTAL_DAYS}e et dernier jour. Rien ne sera publié automatiquement demain sauf si le cron ou la campagne est relancé(e).`
      );
    }
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : String(err);
    console.error(`[daily-instagram-post] Jour ${dayNumber} échoué:`, err);
    await saveResultStep({
      dayNumber,
      pillarKey: pillar.key,
      headline: "",
      caption: "",
      imageUrl: "",
      status: "failed",
      errorMessage,
    });
    await alertStep(
      `Échec jour ${dayNumber}/${CAMPAIGN_TOTAL_DAYS}`,
      `La publication automatique du jour ${dayNumber} a échoué et n'a PAS été publiée.\n\nPilier prévu : ${pillar.label}\nErreur : ${errorMessage}\n\nCauses fréquentes : token Instagram expiré (voir src/lib/instagram.ts), quota Gemini dépassé, bucket Supabase inaccessible. Le prochain run reprendra au même day_number (pas de doublon), donc rien à faire sauf corriger la cause avant demain.`
    );
  }
}
